### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir, 
I have added the API boxes in the README.md file .
please check my PR & after reviewing if possible please merge it under APERTRE'24.

### CODE REVIEW

**Comment by apu52** [comment]
@Sukrittt Please take a look at the PR & after review if possible please merge it under APERTRE'24

**Review by Sukrittt — APPROVED** [review]

**Comment by apu52** [comment]
@Sukrittt Can you please add the APERTRE labels in this PR according to your review . Otherwise My point will not be counted

**Comment by apu52** [comment]
@Sukrittt Can you please add the APERTRE labels in this PR according to your review . Otherwise My point will not be counted

**Comment by Soumyajit2825** [comment]
Hey @Sukrittt @sukrit101 are you there?

**Comment by Sukrittt** [comment]
Sorry, was out for a few days. I've added the label.

**Comment by Soumyajit2825** [comment]
> Sorry, was out for a few days. I've added the label.

add the label as 'apertre' and add difficulty label like 'easy', 'medium', 'hard' in the label

**Comment by Soumyajit2825** [comment]
@Sukrittt @sukrit101

**Comment by apu52** [comment]
@Sukrittt Sir please add labels "easy" , "medium" or "hard" so that my point will be counted. Please sir

**Comment by apu52** [comment]
@Sukrittt Sir , please add the labels

**Pull request merged**
